/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;
import modele.RegistreTransaction;
import modele.RegistreTransaction;
import ui.DashbordFrame;

/**
 *
 * @author ranae
 */
public class AuthFrame extends javax.swing.JFrame {
    private  RegistreTransaction listing;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuthFrame.class.getName());

    /**
     * Creates new form AuthFrame
     */
    public AuthFrame(RegistreTransaction listing) {
        initComponents();
        this.listing = listing;
        setTitle("Authentification");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        lblconx = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        lblmot = new javax.swing.JLabel();
        btnconnecte = new javax.swing.JButton();
        lblcmp = new javax.swing.JLabel();
        lblcompt = new javax.swing.JLabel();
        lblinscription = new javax.swing.JLabel();
        txtmotdepasse = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 227, 199));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusCycleRoot(true);

        lblconx.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lblconx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Connectez-vous a votre compte de la Financiere RK");

        lblnom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblnom.setText("Nom utilisateur :");

        txtnom.addActionListener(this::txtnomActionPerformed);

        lblmot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblmot.setText("Mot de passe :");

        btnconnecte.setBackground(new java.awt.Color(135, 203, 222));
        btnconnecte.setText("SE CONNECTER");
        btnconnecte.addActionListener(this::btnconnecteActionPerformed);

        lblcompt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcompt.setText("Vous n'avez pas encore de compte en ligne ? ");

        lblinscription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblinscription.setText("INSCRIVEZ-VOUS ICI");
        lblinscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblinscriptionMouseClicked(evt);
            }
        });

        txtmotdepasse.addActionListener(this::txtmotdepasseActionPerformed);

        jLabel2.setText("Nom : admin");

        jLabel3.setText("Mot de passe : 1234 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblcompt)
                                .addGap(66, 66, 66)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcmp, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblconx, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmot, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmotdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblinscription))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnconnecte, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblconx, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblnom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblmot)
                .addGap(18, 18, 18)
                .addComponent(txtmotdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblcmp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnconnecte, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblcompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblinscription)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void lblinscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinscriptionMouseClicked
        // TODO add your handling code here:
        try {
        // Remplace par ton URL inscription (ex: site banque)
        Desktop.getDesktop().browse(new URI("https://www.example-banque.com/inscription"));
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erreur ouverture lien : " + ex.getMessage());
    }
    }//GEN-LAST:event_lblinscriptionMouseClicked

    private void btnconnecteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconnecteActionPerformed
        // TODO add your handling code here:
        //DashbordFrame fendash = new DashbordFrame(listing);
       // fendash.setVisible(true);
    String nomUser = txtnom.getText();  // Remplace par TON JTextField nom
    String motPass = new String(txtmotdepasse.getPassword());  // TON JPasswordField
    
    try {
        // Vérif vide
        if (nomUser.isEmpty() || motPass.isEmpty()) {
            throw new IllegalArgumentException("Nom utilisateur et mot de passe requis !");
        }
        
        // Vérif identifiants (tes valeurs)
        if ("admin".equals(nomUser) && "1234".equals(motPass)) {
            // Connexion OK → Ouvre DashbordFrame
            DashbordFrame fendash = new DashbordFrame(listing);
             fendash.setVisible(true);
             this.dispose();  // Ferme fenêtre login
        } else {
            throw new Exception("Identifiants incorrects !");
        }
        
    } catch (Exception ex) {  
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur Connexion", JOptionPane.ERROR_MESSAGE);
        txtnom.setText("");
        txtmotdepasse.setText("");
        txtnom.requestFocus();
    }

    }//GEN-LAST:event_btnconnecteActionPerformed

    private void txtmotdepasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmotdepasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmotdepasseActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(() -> new AuthFrame().setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconnecte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblcmp;
    private javax.swing.JLabel lblcompt;
    private javax.swing.JLabel lblconx;
    private javax.swing.JLabel lblinscription;
    private javax.swing.JLabel lblmot;
    private javax.swing.JLabel lblnom;
    private javax.swing.JPasswordField txtmotdepasse;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
