/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import io.ManipFichier;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import modele.RegistreTransaction;
import modele.Transaction;

/**
 *
 * @author ranae
 */
public class TransactionFrame extends javax.swing.JFrame {
    private RegistreTransaction lisitng;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionFrame.class.getName());

    /**
     * Creates new form TransactionFrame
     */
    //  Color BG = Color.decode("#E3F2FD");
  //    Color PANEL = Color.decode("#C8E6C9"); 
      
    public TransactionFrame(RegistreTransaction listing) {
        initComponents();
         setTitle("Transaction");
           this.lisitng = listing; 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbldescription = new javax.swing.JLabel();
        lblmontant = new javax.swing.JLabel();
        lbltype = new javax.swing.JLabel();
        txtmontant = new javax.swing.JTextField();
        boxdescription = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnajouter = new javax.swing.JButton();
        btnannuler = new javax.swing.JButton();
        btnretour = new javax.swing.JButton();
        boxtype = new javax.swing.JComboBox<>();
        boxdate1 = new javax.swing.JComboBox<>();
        boxdate2 = new javax.swing.JComboBox<>();
        boxdate3 = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 255, 252));

        jPanel2.setBackground(new java.awt.Color(199, 232, 205));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText(" Nouvelle Transaction ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lbldate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldate.setText("Date : ");

        lbldescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldescription.setText("Description :");

        lblmontant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblmontant.setText("Montant : ");

        lbltype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltype.setText("Type de transaction  : ");

        boxdescription.setEditable(true);
        boxdescription.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HydroQuebec", "Telephone Bell ", "Epecerie", "Loyer", "Transport ", "SAAQ", " " }));
        boxdescription.addActionListener(this::boxdescriptionActionPerformed);

        jPanel4.setBackground(new java.awt.Color(199, 232, 205));

        btnajouter.setBackground(new java.awt.Color(135, 203, 222));
        btnajouter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(this::btnajouterActionPerformed);

        btnannuler.setBackground(new java.awt.Color(135, 203, 222));
        btnannuler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnannuler.setText("Annuler");

        btnretour.setBackground(new java.awt.Color(135, 203, 222));
        btnretour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnretour.setText("Retour");
        btnretour.addActionListener(this::btnretourActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnretour)
                .addGap(42, 42, 42)
                .addComponent(btnajouter)
                .addGap(38, 38, 38)
                .addComponent(btnannuler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajouter)
                    .addComponent(btnannuler)
                    .addComponent(btnretour))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        boxtype.setEditable(true);
        boxtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Depot", "Paiement " }));
        boxtype.addActionListener(this::boxtypeActionPerformed);

        boxdate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        boxdate2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janvier", " ", "février", " ", "mars", " ", "avril", " ", "mai", " ", "juin", " ", "juillet", " ", "août", " ", "septembre", " ", "octobre", " ", "novembre", " ", "décembre", " ", " " }));
        boxdate2.addActionListener(this::boxdate2ActionPerformed);

        boxdate3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026" }));
        boxdate3.addActionListener(this::boxdate3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldescription, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boxdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxdate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lbltype, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxtype, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 93, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxdate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lbldescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblmontant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltype)
                    .addComponent(boxtype, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_btnretourActionPerformed

    private void boxdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxdescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxdescriptionActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        // TODO add your handling code here:
        try {
        // ✅ Date complète : jour/mois/annee
        int jour = Integer.parseInt((String) boxdate1.getSelectedItem());
          String mois = (String) boxdate2.getSelectedItem();
       
        int annee = Integer.parseInt((String) boxdate3.getSelectedItem());
        
        String date = jour + "/" + mois + "/" + annee; 

        String description = (String) boxdescription.getSelectedItem();
        double montant = Double.parseDouble(txtmontant.getText().trim());
        String type = (String) boxtype.getSelectedItem();  // Séparé de description !

        // Créer Transaction
        Transaction t = new Transaction();
        t.setDate(date);
        t.setDescription(description);
        t.setMontant(montant);
        t.setType(type);

        // Ajouter et sauvegarder
        RegistreTransaction.getInstance().ajouter(t);
        ManipFichier.sauvegarder(RegistreTransaction.getInstance().getRegistre());

        JOptionPane.showMessageDialog(this, "Transaction ajoutée : " + date, "Succès", JOptionPane.INFORMATION_MESSAGE);

        // ✅ Reset CORRECT (pas txtdate qui n'existe pas)
        boxdate1.setSelectedIndex(0);
        boxdate2.setSelectedIndex(0);
        boxdate3.setSelectedIndex(0);
        boxdescription.setSelectedIndex(0);
        if (boxtype != null) boxtype.setSelectedIndex(0);
        txtmontant.setText("");
        txtmontant.requestFocus();

    } catch (NumberFormatException | NullPointerException e) {
        JOptionPane.showMessageDialog(this, "Vérifiez : jour/année (nombres), montant valide, tous champs remplis !", "Erreur saisie", JOptionPane.ERROR_MESSAGE);
        txtmontant.requestFocus();
    }
    }//GEN-LAST:event_btnajouterActionPerformed

    private void boxtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtypeActionPerformed

    private void boxdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxdate2ActionPerformed

    private void boxdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxdate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxdate3ActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(() -> new TransactionFrame(listing).setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxdate1;
    private javax.swing.JComboBox<String> boxdate2;
    private javax.swing.JComboBox<String> boxdate3;
    private javax.swing.JComboBox<String> boxdescription;
    private javax.swing.JComboBox<String> boxtype;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnannuler;
    private javax.swing.JButton btnretour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldescription;
    private javax.swing.JLabel lblmontant;
    private javax.swing.JLabel lbltype;
    private javax.swing.JTextField txtmontant;
    // End of variables declaration//GEN-END:variables

   

   

}
